# Generated by Django 5.2.7 on 2025-10-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50)),
                ('best_role', models.CharField(max_length=50)),
                ('corners', models.SmallIntegerField(default=0)),
                ('crossing', models.SmallIntegerField(default=0)),
                ('dribbling', models.SmallIntegerField(default=0)),
                ('finishing', models.SmallIntegerField(default=0)),
                ('first_touch', models.SmallIntegerField(default=0)),
                ('free_kicks', models.SmallIntegerField(default=0)),
                ('heading', models.SmallIntegerField(default=0)),
                ('long_shots', models.SmallIntegerField(default=0)),
                ('long_throws', models.SmallIntegerField(default=0)),
                ('marking', models.SmallIntegerField(default=0)),
                ('passing', models.SmallIntegerField(default=0)),
                ('penalty_taking', models.SmallIntegerField(default=0)),
                ('tackling', models.SmallIntegerField(default=0)),
                ('technique', models.SmallIntegerField(default=0)),
                ('aggression', models.SmallIntegerField(default=0)),
                ('anticipation', models.SmallIntegerField(default=0)),
                ('bravery', models.SmallIntegerField(default=0)),
                ('composure', models.SmallIntegerField(default=0)),
                ('concetration', models.SmallIntegerField(default=0)),
                ('decisions', models.SmallIntegerField(default=0)),
                ('determination', models.SmallIntegerField(default=0)),
                ('flair', models.SmallIntegerField(default=0)),
                ('leadership', models.SmallIntegerField(default=0)),
                ('off_the_ball', models.SmallIntegerField(default=0)),
                ('positioning', models.SmallIntegerField(default=0)),
                ('teamwork', models.SmallIntegerField(default=0)),
                ('vision', models.SmallIntegerField(default=0)),
                ('work_rate', models.SmallIntegerField(default=0)),
                ('acceleration', models.SmallIntegerField(default=0)),
                ('pace', models.SmallIntegerField(default=0)),
                ('agility', models.SmallIntegerField(default=0)),
                ('balance', models.SmallIntegerField(default=0)),
                ('jumping_reach', models.SmallIntegerField(default=0)),
                ('stamina', models.SmallIntegerField(default=0)),
                ('strength', models.SmallIntegerField(default=0)),
                ('natural_fitness', models.SmallIntegerField(default=0)),
                ('gk_diving', models.SmallIntegerField(default=0)),
                ('gk_handling', models.SmallIntegerField(default=0)),
                ('gk_kicking', models.SmallIntegerField(default=0)),
                ('gk_reflexes', models.SmallIntegerField(default=0)),
                ('gk_positioning', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
